### ISSUE TITLE
Add to latest Companion beta 

### ISSUE THREAD

**Issue by tpk001** [bitfocus/companion-module-broadlink-remote#2]
Can you please add this to the latest Companion 3.3.0 beta branch?

**Comment by tpk001** [comment]
@leonreucher @Julusian
Seems the module is working as I can see in the previously closed issue.
Can you please push it to the latest beta branch?
Thanks.

**Comment by tpk001** [comment]
Any update on added this module to the beta branch please?

**Comment by tpk001** [comment]
Hi @Julusian, Would you be able to help with getting this to the current beta of Companion?
Thanks.

**Comment by BenJamesAndo** [comment]
You might be better off asking in the Slack Chat: https://bitfocusio.slack.com
From what I understand a module needs to be at least version 1.0 for it to be included in the beta. Also the README says wled-ws instead of broadlink.

**Comment by leonreucher** [comment]
Sorry, lot of work - just programming some stuff when I find free time in my schedule. I released v1.0.0 and asked for inclusion to the next version.
