### ISSUE TITLE
Setup HowTo?

### ISSUE THREAD

**Issue by dog199200** [bitfocus/companion-module-broadlink-remote#3]
So I downloaded the source, and added it to the bundled-modules file for companion, but I am having issues. Is there a specific way this has to be compiled for it to work?

Asking because I am getting an (Cannot Find package "@companion-modular/base")  error, so I am assuming I am assuming I added it to the wrong spot, am missing a dependency, OR it has to be compiled in a specific way I am unaware of.

**Comment by leonreucher** [comment]
Module is now included in Companion, therefore no manual interaction is needed.
