### ISSUE TITLE
A couple of issues with v1.0.0

### ISSUE THREAD

**Issue by tpk001** [bitfocus/companion-module-broadlink-remote#4]
Thanks for the effort in getting this module out.

Few issues:
1. Will not be able to start the connection if the rm4pro in different subnet than Companion. (e.g. Companion on 10.0.100.1 and rm4pros on 10.10.200.x
2. When you add multiple devices, once a device added it does not respect the IP address for the second device. It uses the first devices connection even for the second device.

Thanks

**Comment by mrhhats** [comment]
Just my 2 cents. #1 must be why my setup won't work and I posted it as a seperate thread/issue.

Glad its not just me
